server:
  port: 0 # 這會產生隨機port號

spring:
  application:
    name: ms-provider

eureka:
  instance:
    prefer-ip-address: true #以IP地址注册到服务中心
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://140.134.26.71:50608/eureka/
